using System.Collections.Generic;
using UnityEngine;

public class LevelData : MonoBehaviour {
    // TODO: after completing your level simply put the number of coins u put in the level in array's length below
    public static Dictionary<string, bool[]> coinsAlreadyCollected = new Dictionary<string, bool[]>{
      {"RowingTutorial", new bool[0]},
      {"newRacing", new bool[0]},
      {"Level1", new bool[3]},
      {"Level2", new bool[6]},
      {"Level3", new bool[6]},
      {"Level4", new bool[6]},
      {"Level5", new bool[9]},
      {"Level6", new bool[13]},
      {"Level7", new bool[12]},
      {"Level8", new bool[9]},
      {"Level9", new bool[11]},
      {"Level10", new bool[11]},
      {"Level11", new bool[11]},
      {"Level12", new bool[11]},
      {"Level13", new bool[9]},
      {"Level14", new bool[9]},
      {"Level15", new bool[9]},
      {"Level16", new bool[9]}
    };
    public static Dictionary<string, int> levelNewCompletionGoldRewards = new Dictionary<string, int>{
      {"RowingTutorial", 5},
      {"newRacing", 5},
      {"Level1", 5},
      {"Level2", 5},
      {"Level3", 5},
      {"Level4", 10},
      {"Level5", 10},
      {"Level6", 10},
      {"Level7", 15},
      {"Level8", 15},
      {"Level9", 15},
      {"Level10", 20},
      {"Level11", 20},
      {"Level12", 20},
      {"Level13", 20},
      {"Level14", 20},
      {"Level15", 20},
      {"Level16", 20},
    };
    public static Dictionary<string, int> levelStaleCompletionGoldRewards = new Dictionary<string, int>{
      {"RowingTutorial", 1},
      {"newRacing", 1},
      {"Level1", 2},
      {"Level2", 2},
      {"Level3", 2},
      {"Level4", 4},
      {"Level5", 4},
      {"Level6", 4},
      {"Level7", 8},
      {"Level8", 8},
      {"Level9", 8},
      {"Level10", 12},
      {"Level11", 12},
      {"Level12", 12},
      {"Level13", 12},
      {"Level14", 12},
      {"Level15", 12},
      {"Level16", 12},
    };
    public static Dictionary<string, int> TotalLaps = new Dictionary<string, int>{
      {"RowingTutorial", 1},
      {"newRacing", 1},
      {"Level1", 1},
      {"Level2", 1},
      {"Level3", 1},
      {"Level4", 1},
      {"Level5", 3},
      {"Level6", 1},
      {"Level7", 2},
      {"Level8", 2},
      {"Level9", 1},
      {"Level10", 1},
      {"Level11", 1},
      {"Level12", 1},
      {"Level13", 1},
      {"Level14", 1},
      {"Level15", 1},
      {"Level16", 1},
    };
}